# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enginery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree.Node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeMachineToolRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_tool_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enginery.MachineToolSpecification')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Node')),
            ],
        ),
    ]
