# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machinery', '0002_auto_20171007_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('machinery', models.ManyToManyField(to='machinery.Machine')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Node')),
            ],
        ),
    ]
