# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='machinery',
            field=models.ManyToManyField(blank=True, to='machinery.Machine'),
        ),
        migrations.AlterField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Node'),
        ),
    ]
