# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enginery', '0001_initial'),
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineToolSpecificationInNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_tool_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enginery.MachineToolSpecification')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Node')),
            ],
        ),
        migrations.RemoveField(
            model_name='nodemachinetoolrequirement',
            name='machine_tool_requirement',
        ),
        migrations.RemoveField(
            model_name='nodemachinetoolrequirement',
            name='node',
        ),
        migrations.DeleteModel(
            name='NodeMachineToolRequirement',
        ),
    ]
