# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tree',
            new_name='Node',
        ),
    ]
