# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20171130_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='name',
            new_name='value',
        ),
    ]
