# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20171130_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='tree.Node')),
            ],
        ),
    ]
