# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0005_auto_20171129_2055'),
        ('tree', '0008_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagMachineToolRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_tool_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolRequirement')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tree.Node'),
        ),
        migrations.AddField(
            model_name='tagmachinetoolrequirement',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Tag'),
        ),
    ]
