# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0005_auto_20171129_2055'),
        ('tree', '0009_auto_20171210_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMachineToolRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_tool_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolRequirement')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Node')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='node',
        ),
        migrations.RemoveField(
            model_name='tagmachinetoolrequirement',
            name='machine_tool_requirement',
        ),
        migrations.RemoveField(
            model_name='tagmachinetoolrequirement',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagMachineToolRequirement',
        ),
    ]
