# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarFeeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('minimum_stock_diameter', models.CharField(max_length=15)),
                ('maximum_stock_diameter', models.CharField(max_length=15)),
                ('maximum_stock_length', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chuck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('object_id', models.PositiveIntegerField()),
                ('minimum_part_diameter', models.CharField(max_length=15)),
                ('maximum_part_diameter', models.CharField(max_length=15)),
                ('number_of_jaws', models.CharField(max_length=15)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CircularWorkTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('number_of_t_slots', models.CharField(blank=True, max_length=15, null=True)),
                ('t_slots_size', models.CharField(blank=True, max_length=15, null=True)),
                ('distance_between_t_slot_centers', models.CharField(blank=True, max_length=15, null=True)),
                ('rotatable', models.BooleanField()),
                ('workpiece_weight', models.CharField(blank=True, max_length=15, null=True)),
                ('fixture_style', models.CharField(blank=True, choices=[(b'CHUCK_FIXTURE', b'chuck fixture'), (b'HOLE', b'hole'), (b'T_SLOT_FIXTURE', b't slot fixture'), (b'VACUUM', b'vacuum')], max_length=25, null=True)),
                ('table_diameter', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('collet_type', models.CharField(max_length=15)),
                ('minimum_part_diameter', models.CharField(max_length=15)),
                ('maximum_part_diameter', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContinuousRotary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('axis_name', models.CharField(max_length=15)),
                ('displacement_angle_error', models.CharField(max_length=15)),
                ('repeatability_angle_error', models.CharField(max_length=15)),
                ('rapid_traverse_rotation_feed_rate', models.CharField(max_length=15)),
                ('minimum_cutting_rotation_feed_rate', models.CharField(max_length=15)),
                ('maximum_cutting_rotation_feed_rate', models.CharField(max_length=15)),
                ('maximum_rotation_deceleration', models.IntegerField(blank=True, null=True)),
                ('maximum_rotation_acceleration', models.IntegerField(blank=True, null=True)),
                ('maximum_rotation_jerk', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coolant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('coolant_type', models.CharField(choices=[(b'AIR', b'air'), (b'FLOOD', b'flood'), (b'MICRO', b'micro'), (b'MIST', b'mist'), (b'NONE', b'none')], max_length=25)),
                ('means_of_delivery', models.CharField(blank=True, choices=[(b'EXTERNAL', b'external'), (b'THRU_SPINDLE', b'thru spindle'), (b'THRU_TURRET', b'thru turret')], max_length=25, null=True)),
                ('capacity_of_coolant_tank', models.CharField(blank=True, max_length=15, null=True)),
                ('coolant_weight', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuttingFeedRateOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_feed_rate_override', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CycleFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_function', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('id', models.CharField(max_length=15)),
                ('model_name', models.CharField(max_length=15)),
                ('serial_number', models.CharField(max_length=15)),
                ('manufacturer', models.CharField(max_length=15)),
                ('date_manufactured', models.DateField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ElementLinkAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_link', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_type', models.CharField(max_length=15)),
                ('weight', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_name', models.CharField(max_length=15)),
                ('power_in_idling', models.CharField(blank=True, max_length=15, null=True)),
                ('time_for_warming_up', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indexing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('axis_name', models.CharField(max_length=15)),
                ('displacement_angle_error', models.CharField(max_length=15)),
                ('repeatability_angle_error', models.CharField(max_length=15)),
                ('rapid_traverse_rotation_feed_rate', models.CharField(max_length=15)),
                ('minimum_cutting_rotation_feed_rate', models.CharField(max_length=15)),
                ('maximum_cutting_rotation_feed_rate', models.CharField(max_length=15)),
                ('maximum_rotation_deceleration', models.IntegerField(blank=True, null=True)),
                ('maximum_rotation_acceleration', models.IntegerField(blank=True, null=True)),
                ('maximum_rotation_jerk', models.IntegerField(blank=True, null=True)),
                ('index_increment', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_length', models.CharField(max_length=15)),
                ('machine_width', models.CharField(max_length=15)),
                ('machine_height', models.CharField(max_length=15)),
                ('electric_phase', models.CharField(max_length=15)),
                ('electric_power', models.CharField(max_length=15)),
                ('electrical_current', models.CharField(max_length=15)),
                ('electrical_frequency', models.CharField(max_length=15)),
                ('electrical_grounding', models.CharField(max_length=15)),
                ('electrical_voltage', models.IntegerField()),
                ('type_of_hydraulic_oil', models.CharField(blank=True, max_length=15, null=True)),
                ('pump_outlet_pressure', models.CharField(blank=True, max_length=15, null=True)),
                ('capacity_of_hydraulics_tank', models.CharField(blank=True, max_length=15, null=True)),
                ('weight', models.CharField(max_length=15)),
                ('air_pressure_requirement', models.CharField(blank=True, max_length=15, null=True)),
                ('water_flow_rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterpolationFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_function', models.CharField(choices=[(b'CIRCULAR', b'circular'), (b'HELICAL', b'helical'), (b'LINEAR', b'linear'), (b'NURBS', b'nurbs'), (b'OTHER', b'other')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LimitedSwing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('axis_name', models.CharField(max_length=15)),
                ('displacement_angle_error', models.CharField(max_length=15)),
                ('repeatability_angle_error', models.CharField(max_length=15)),
                ('rapid_traverse_rotation_feed_rate', models.CharField(max_length=15)),
                ('minimum_cutting_rotation_feed_rate', models.CharField(max_length=15)),
                ('maximum_cutting_rotation_feed_rate', models.CharField(max_length=15)),
                ('maximum_rotation_deceleration', models.IntegerField(blank=True, null=True)),
                ('maximum_rotation_acceleration', models.IntegerField(blank=True, null=True)),
                ('maximum_rotation_jerk', models.IntegerField(blank=True, null=True)),
                ('minimum_angle_of_motion', models.CharField(max_length=15)),
                ('maximum_angle_of_motion', models.CharField(max_length=15)),
                ('axis_travel_limit', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinearAxis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('axis_name', models.CharField(max_length=15)),
                ('minimum_range_of_motion', models.CharField(max_length=15)),
                ('maximum_range_of_motion', models.CharField(max_length=15)),
                ('displacement_error', models.CharField(max_length=15)),
                ('repeatability_error', models.CharField(max_length=15)),
                ('rapid_traverse_feed_rate', models.CharField(max_length=15)),
                ('minimum_cutting_feed_rate', models.CharField(max_length=15)),
                ('maximum_cutting_feed_rate', models.CharField(max_length=15)),
                ('maximum_acceleration', models.CharField(blank=True, max_length=15, null=True)),
                ('maximum_deceleration', models.CharField(blank=True, max_length=15, null=True)),
                ('maximum_jerk', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineElementRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MachineKinematicAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinematics', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MachineToolAxis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('axis_name', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineToolElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuring_accuracy', models.CharField(blank=True, max_length=15, null=True)),
                ('measuring_description', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
                ('weight', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineToolRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuring_accuracy', models.CharField(blank=True, max_length=15, null=True)),
                ('measuring_description', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(max_length=15)),
                ('number_of_axes', models.CharField(blank=True, max_length=15, null=True)),
                ('number_of_simultaneous_axes', models.CharField(blank=True, max_length=15, null=True)),
                ('maximum_displacement_error_of_linear_axis', models.CharField(blank=True, max_length=15, null=True)),
                ('maximum_repeatability_error_of_linear_axis', models.CharField(blank=True, max_length=15, null=True)),
                ('number_of_tools_in_tool_magazine', models.CharField(blank=True, max_length=15, null=True)),
                ('automatically_pallet_changeable', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineToolSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('business_unit', models.CharField(blank=True, max_length=15, null=True)),
                ('plant_location', models.CharField(blank=True, max_length=15, null=True)),
                ('building', models.CharField(blank=True, max_length=15, null=True)),
                ('cell', models.CharField(blank=True, max_length=15, null=True)),
                ('machine_class', models.CharField(choices=[(b'DRILLING_MACHINE', b'drilling machine'), (b'GUNDRILL_MACHINE', b'gundrill machine'), (b'MACHINING_CENTRE', b'machining centre'), (b'MILLING_MACHINE', b'milling machine'), (b'MULTI_TASKING_MACHINE', b'multi tasking machine'), (b'TURNING_MACHINE', b'turning machine')], max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachiningCapability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machining_size_description', models.CharField(blank=True, max_length=15, null=True)),
                ('machining_size_x', models.CharField(blank=True, max_length=15, null=True)),
                ('machining_size_y', models.CharField(blank=True, max_length=15, null=True)),
                ('machining_size_z', models.CharField(blank=True, max_length=15, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('capability', models.CharField(choices=[(b'BORING_CAPABILITY', b'boring capability'), (b'DRILLING_CAPABILITY', b'drilling capability'), (b'GUNDRILL_CAPABILITY', b'gundrill capability'), (b'MILLING_CAPABILITY', b'milling capability'), (b'TURNING_CAPABILITY', b'turning capability')], max_length=25)),
                ('machining_accuracy', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NcController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_model', models.CharField(max_length=15)),
                ('controller_manufacturer', models.CharField(max_length=15)),
                ('units', models.CharField(choices=[(b'INCH', b'small'), (b'INCH_AND_METRIC', b'inch and metric'), (b'METRIC', b'metric')], max_length=25)),
                ('maximum_number_of_simultaneous_control_axes', models.CharField(max_length=15)),
                ('maximum_total_number_of_control_feed_axes', models.CharField(max_length=15)),
                ('maximum_total_number_of_control_spindles', models.CharField(max_length=15)),
                ('minimum_linear_increment', models.CharField(max_length=15)),
                ('minimum_angle_increment', models.CharField(max_length=15)),
                ('maximum_number_of_multi_channel_control', models.CharField(max_length=15)),
                ('look_ahead', models.IntegerField(blank=True, null=True)),
                ('adaptive_control', models.CharField(blank=True, max_length=15, null=True)),
                ('miscellaneous_controller_functions', models.CharField(blank=True, max_length=15, null=True)),
                ('program_memory_size', models.IntegerField(blank=True, null=True)),
                ('time_sampling', models.CharField(blank=True, max_length=15, null=True)),
                ('clock_frequency', models.CharField(blank=True, max_length=15, null=True)),
                ('machine_tool_specification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolSpecification')),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('number_of_t_slots', models.CharField(blank=True, max_length=15, null=True)),
                ('t_slots_size', models.CharField(blank=True, max_length=15, null=True)),
                ('distance_between_t_slot_centers', models.CharField(blank=True, max_length=15, null=True)),
                ('rotatable', models.BooleanField()),
                ('workpiece_weight', models.CharField(blank=True, max_length=15, null=True)),
                ('fixture_style', models.CharField(blank=True, choices=[(b'CHUCK_FIXTURE', b'chuck fixture'), (b'HOLE', b'hole'), (b'T_SLOT_FIXTURE', b't slot fixture'), (b'VACUUM', b'vacuum')], max_length=25, null=True)),
                ('random_access', models.BooleanField()),
                ('table_width', models.CharField(max_length=15)),
                ('table_length', models.CharField(max_length=15)),
                ('number_of_pallet', models.CharField(max_length=15)),
                ('storage_configuration', models.CharField(blank=True, choices=[(b'CAROUSEL', b'carousel'), (b'CAROUSEL_2_PLACE', b'carousel 2 place'), (b'CHAIN', b'chain'), (b'FIXED_2_PLACE', b'fixed 2 place'), (b'MULTI_STOREY', b'multi storey'), (b'STRAIGHT_LINE', b'straight line')], max_length=25, null=True)),
                ('pallet_change_time_minimum', models.CharField(blank=True, max_length=15, null=True)),
                ('pallet_change_time_maximum', models.CharField(blank=True, max_length=15, null=True)),
                ('pallet_type', models.CharField(blank=True, max_length=15, null=True)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartProbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('probe_type', models.CharField(choices=[(b'NULLING', b'nulling'), (b'PROPORTIONAL', b'proportional'), (b'SWITCHING', b'switching')], max_length=25)),
                ('dimensionality', models.CharField(choices=[(b'ONE_D', b'one d'), (b'TWO_D', b'two d'), (b'THREE_D', b'three d')], max_length=25)),
                ('setting_time', models.CharField(max_length=15)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPhysicalResourceAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_of_resource', models.CharField(max_length=15)),
                ('machine_tool_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolRequirement')),
            ],
        ),
        migrations.CreateModel(
            name='RangeOfMotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_name', models.CharField(max_length=15)),
                ('motion_range', models.IntegerField()),
                ('positioning_capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolRequirement')),
            ],
        ),
        migrations.CreateModel(
            name='RapidTraverseOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapid_traverse_override', models.CharField(max_length=15)),
                ('nc_controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.NcController')),
            ],
        ),
        migrations.CreateModel(
            name='RectangularWorkTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('number_of_t_slots', models.CharField(blank=True, max_length=15, null=True)),
                ('t_slots_size', models.CharField(blank=True, max_length=15, null=True)),
                ('distance_between_t_slot_centers', models.CharField(blank=True, max_length=15, null=True)),
                ('rotatable', models.BooleanField()),
                ('workpiece_weight', models.CharField(blank=True, max_length=15, null=True)),
                ('fixture_style', models.CharField(blank=True, choices=[(b'CHUCK_FIXTURE', b'chuck fixture'), (b'HOLE', b'hole'), (b'T_SLOT_FIXTURE', b't slot fixture'), (b'VACUUM', b'vacuum')], max_length=25, null=True)),
                ('table_width', models.CharField(max_length=15)),
                ('table_length', models.CharField(max_length=15)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spindle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('spindle_power', models.CharField(max_length=15)),
                ('spindle_name', models.CharField(max_length=15)),
                ('spindle_manufacturer', models.CharField(blank=True, max_length=15, null=True)),
                ('manufacturer_model_designation', models.CharField(blank=True, max_length=15, null=True)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpindleCapability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spindle_name', models.CharField(max_length=15)),
                ('spindle_power', models.CharField(max_length=15)),
                ('maximum_drive_speed', models.CharField(max_length=15)),
                ('machine_tool_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolRequirement')),
            ],
        ),
        migrations.CreateModel(
            name='SpindleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spindle_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SpindleRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('minimum_drive_speed', models.CharField(max_length=15)),
                ('maximum_drive_speed', models.CharField(max_length=15)),
                ('minimum_drive_torque', models.IntegerField()),
                ('maximum_drive_torque', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='StandardMachiningProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_description', models.CharField(max_length=15)),
                ('type_of_machining', models.CharField(max_length=15)),
                ('power', models.CharField(max_length=15)),
                ('electric_power', models.CharField(max_length=15)),
                ('environmental_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.EnvironmentalEvaluation')),
            ],
        ),
        migrations.CreateModel(
            name='StraightSpindle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('spindle_power', models.CharField(max_length=15)),
                ('spindle_name', models.CharField(max_length=15)),
                ('spindle_manufacturer', models.CharField(blank=True, max_length=15, null=True)),
                ('manufacturer_model_designation', models.CharField(blank=True, max_length=15, null=True)),
                ('spindle_tool_holder_style_designation', models.CharField(max_length=15)),
                ('coolant_through_spindle', models.BooleanField()),
                ('spindle_bore_depth', models.CharField(max_length=15)),
                ('spindle_bore_diameter', models.CharField(max_length=15)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tailstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('spindle_name', models.CharField(max_length=15)),
                ('taper', models.CharField(max_length=15)),
                ('maximum_workpiece_weight_of_quill', models.CharField(max_length=15)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaperedSpindle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('spindle_power', models.CharField(max_length=15)),
                ('spindle_name', models.CharField(max_length=15)),
                ('spindle_manufacturer', models.CharField(blank=True, max_length=15, null=True)),
                ('manufacturer_model_designation', models.CharField(blank=True, max_length=15, null=True)),
                ('spindle_tool_holder_style_designation', models.CharField(max_length=15)),
                ('coolant_through_spindle', models.BooleanField()),
                ('spindle_taper_designation', models.CharField(max_length=15)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreadedSpindle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('spindle_power', models.CharField(max_length=15)),
                ('spindle_name', models.CharField(max_length=15)),
                ('spindle_manufacturer', models.CharField(blank=True, max_length=15, null=True)),
                ('manufacturer_model_designation', models.CharField(blank=True, max_length=15, null=True)),
                ('spindle_tool_holder_style_designation', models.CharField(max_length=15)),
                ('coolant_through_spindle', models.BooleanField()),
                ('spindle_thread_diameter', models.CharField(max_length=15)),
                ('spindle_thread_pitch', models.CharField(max_length=15)),
                ('spindle_thread_form', models.CharField(max_length=15)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tool_number', models.CharField(max_length=15)),
                ('tool_type', models.CharField(max_length=15)),
                ('tool_size', models.CharField(blank=True, max_length=15, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ToolBreakage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolChanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('spindle_name', models.CharField(max_length=15)),
                ('cut_to_cut_min_tool_change_time', models.CharField(blank=True, max_length=15, null=True)),
                ('cut_to_cut_max_tool_change_time', models.CharField(blank=True, max_length=15, null=True)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolCompensationFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_compensation_function', models.CharField(choices=[(b'TOOL_LENGTH', b'tool length'), (b'TOOL_RADIUS', b'tool radius')], max_length=25)),
                ('nc_controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.NcController')),
            ],
        ),
        migrations.CreateModel(
            name='ToolMagazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('number_of_tools', models.CharField(max_length=15)),
                ('random_access', models.BooleanField()),
                ('diameter_full', models.CharField(max_length=15)),
                ('diameter_empty', models.CharField(max_length=15)),
                ('tool_length', models.CharField(max_length=15)),
                ('tool_weight', models.CharField(max_length=15)),
                ('storage_configuration', models.CharField(blank=True, choices=[(b'BI_DIRECTIONAL', b'bi directional'), (b'BOX_MATRIX', b'box matrix'), (b'UNI_DIRECTIONAL', b'uni directional')], max_length=25, null=True)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('measuring_radius', models.BooleanField()),
                ('measuring_length', models.BooleanField()),
                ('measure_time', models.CharField(max_length=15)),
                ('probe_type', models.CharField(choices=[(b'NULLING', b'nulling'), (b'PROPORTIONAL', b'proportional'), (b'SWITCHING', b'switching')], max_length=25)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('number_of_fixed_tools', models.CharField(max_length=15)),
                ('number_of_rotating_tools', models.CharField(max_length=15)),
                ('cut_to_cut_min_turret_index_time', models.CharField(blank=True, max_length=15, null=True)),
                ('cut_to_cut_max_turret_index_time', models.CharField(blank=True, max_length=15, null=True)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkplanPhysicalResourceAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplan_of_resource', models.CharField(max_length=15)),
                ('machine_tool_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolRequirement')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpindle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
                ('spindle_power', models.CharField(max_length=15)),
                ('spindle_name', models.CharField(max_length=15)),
                ('spindle_manufacturer', models.CharField(blank=True, max_length=15, null=True)),
                ('manufacturer_model_designation', models.CharField(blank=True, max_length=15, null=True)),
                ('spindle_nose_designation', models.CharField(max_length=15)),
                ('spindle_bore_diameter', models.CharField(max_length=15)),
                ('round_bar_stock_diameter', models.CharField(blank=True, max_length=15, null=True)),
                ('through_hole_diameter', models.CharField(blank=True, max_length=15, null=True)),
                ('hex_bar_stock_capacity', models.IntegerField(blank=True, null=True)),
                ('machine_tool_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='spindlename',
            name='turret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.Turret'),
        ),
        migrations.AddField(
            model_name='machinetoolelement',
            name='machine_tool_specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolSpecification'),
        ),
        migrations.AddField(
            model_name='machinetoolaxis',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='machinekinematicassociation',
            name='machine_kinematic_association',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolSpecification'),
        ),
        migrations.AddField(
            model_name='machineelementrelationship',
            name='former_element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='former_element_to_MachineToolElement', to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='machineelementrelationship',
            name='latter_element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latter_element_to_MachineToolElement', to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='linearaxis',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='limitedswing',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='interpolationfunction',
            name='nc_controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.NcController'),
        ),
        migrations.AddField(
            model_name='installation',
            name='machine_tool_specification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolSpecification'),
        ),
        migrations.AddField(
            model_name='indexing',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='environmentalevaluation',
            name='machine_tool_specification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolSpecification'),
        ),
        migrations.AddField(
            model_name='emissionproperty',
            name='environmental_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.StandardMachiningProcess'),
        ),
        migrations.AddField(
            model_name='elementlinkassociation',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='cyclefunction',
            name='nc_controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.NcController'),
        ),
        migrations.AddField(
            model_name='cuttingfeedrateoverride',
            name='nc_controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.NcController'),
        ),
        migrations.AddField(
            model_name='coolant',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='continuousrotary',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='collet',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='circularworktable',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='chuck',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
        migrations.AddField(
            model_name='barfeeder',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolElement'),
        ),
    ]
