# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MeasuringCapability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuring_accuracy', models.CharField(max_length=15)),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineToolRequirements',
            fields=[
                ('machinetool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machinery.MachineTool')),
                ('touch_probing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machinery.MeasuringCapability')),
            ],
            bases=('machinery.machinetool',),
        ),
    ]
