# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetoolrequirements',
            name='automatically_pallet_changeable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
