# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collet',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collet', to='machinery.MachineToolElement'),
        ),
    ]
