# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousrotary',
            name='maximum_rotation_acceleration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='continuousrotary',
            name='maximum_rotation_deceleration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='continuousrotary',
            name='maximum_rotation_jerk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='maximum_rotation_acceleration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='maximum_rotation_deceleration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='maximum_rotation_jerk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limitedswing',
            name='maximum_rotation_acceleration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limitedswing',
            name='maximum_rotation_deceleration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limitedswing',
            name='maximum_rotation_jerk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linearaxis',
            name='maximum_jerk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spindlerange',
            name='maximum_drive_torque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spindlerange',
            name='minimum_drive_torque',
            field=models.IntegerField(),
        ),
    ]
