# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='weight',
        ),
        migrations.AddField(
            model_name='machine',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='providers.Firm'),
            preserve_default=False,
        ),
    ]
