# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_auto_20171129_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barfeeder',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barfeeders', to='machinery.MachineToolElement'),
        ),
        migrations.AlterField(
            model_name='collet',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collets', to='machinery.MachineToolElement'),
        ),
        migrations.AlterField(
            model_name='continuousrotary',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuousrotary', to='machinery.MachineToolElement'),
        ),
        migrations.AlterField(
            model_name='coolant',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coolants', to='machinery.MachineToolElement'),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexing', to='machinery.MachineToolElement'),
        ),
        migrations.AlterField(
            model_name='limitedswing',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limitedswing', to='machinery.MachineToolElement'),
        ),
        migrations.AlterField(
            model_name='tailstock',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailstocks', to='machinery.MachineToolElement'),
        ),
    ]
