# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0003_auto_20171127_2304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tslot',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tslot',
            name='content_type',
        ),
        migrations.AddField(
            model_name='circularworktable',
            name='distance_between_t_slot_centers',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='circularworktable',
            name='number_of_t_slots',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='circularworktable',
            name='t_slots_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='distance_between_t_slot_centers',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='number_of_t_slots',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='t_slots_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rectangularworktable',
            name='distance_between_t_slot_centers',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rectangularworktable',
            name='number_of_t_slots',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rectangularworktable',
            name='t_slots_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='TSlot',
        ),
    ]
