# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0003_auto_20171129_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearaxis',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linearaxis', to='machinery.MachineToolElement'),
        ),
        migrations.AlterField(
            model_name='machinetoolaxis',
            name='machine_tool_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinetoolaxis', to='machinery.MachineToolElement'),
        ),
    ]
