# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0003_auto_20171021_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpindleCapability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spindle_name', models.CharField(max_length=15)),
                ('spindle_power', models.CharField(max_length=15)),
                ('maximum_drive_speed', models.CharField(max_length=15)),
                ('machine_tool_requirements_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolRequirements')),
            ],
            options={
                'db_table': 'spindle_capability',
            },
        ),
        migrations.AlterModelTable(
            name='axiscapability',
            table='axis_capability',
        ),
        migrations.AlterModelTable(
            name='machinetool',
            table='machine_tool',
        ),
        migrations.AlterModelTable(
            name='measuringcapability',
            table='measuring_capability',
        ),
        migrations.AlterModelTable(
            name='positioningcapability',
            table='positioning_capability',
        ),
        migrations.AlterModelTable(
            name='rangeofmotion',
            table='Rangeo_of_motion',
        ),
    ]
