# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0004_auto_20171021_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
                ('x', models.CharField(max_length=15)),
                ('y', models.CharField(max_length=15)),
                ('z', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MachiningCapability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('BORING', 'BORING_CAPABILITY'), ('DRILLING', 'DRILLING_CAPABILITY'), ('GUNDRILL', 'GUNDRILL_CAPABILITY'), ('MILLING', 'MILLING_CAPABILITY'), ('TURNING', 'TURNING_CAPABILITY')], max_length=15)),
                ('machining_accuracy', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
                ('machining_size', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineSize')),
            ],
            options={
                'db_table': 'machining_capability',
            },
        ),
        migrations.AddField(
            model_name='machinetoolrequirements',
            name='number_of_tools_in_tool_magazine',
            field=models.CharField(default=10, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinetoolrequirements',
            name='machining',
            field=models.ManyToManyField(to='machinery.MachiningCapability'),
        ),
    ]
