# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0004_auto_20171127_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineKinematicAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinematics', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='machinetoolspecification',
            name='kinematics',
        ),
        migrations.AlterField(
            model_name='machinetoolspecification',
            name='building',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='machinetoolspecification',
            name='business_unit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='machinetoolspecification',
            name='cell',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='machinetoolspecification',
            name='plant_location',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='machinekinematicassociation',
            name='machine_kinematic_association',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machinery.MachineToolSpecification'),
        ),
    ]
