# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0005_auto_20171021_1852'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rangeofmotion',
            table='range_of_motion',
        ),
    ]
