# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0006_auto_20171128_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='capacity_of_hydraulics_tank',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='pump_outlet_pressure',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='type_of_hydraulic_oil',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
